bib-rekursionsgleichungen:
  type: article
  title: Lösen von (linearen) Rekursionsgleichungen
  author: Robert F. P. Hartmann
  date: 2007-02-27
  organization: Technische Universität Clausthal
  url: https://www2.inf.h-brs.de/~rhartm2m/tuc/inf1-ws2006-07_zusatzmaterial-rekursionsgleichungen.pdf

bib-fibonaccis-rabbits:
  type: web
  title: Fibonacci's Rabbits
  organization: Emory Oxford College
  url: https://mathcenter.oxford.emory.edu/site/math125/fibonacciRabbits/

bib-3b1b-eigenvalues:
  type: chapter
  title: Eigenvectors and Eigenvalues
  url: https://www.3blue1brown.com/lessons/eigenvalues
  author: Grant Sanderson
  issue: 14
  parent:
    title: Essence of Linear Algebra

bib-hanoi-reducible:
  type: video
  title: "Towers of Hanoi: A Complete Recursive Visualization"
  url: https://www.youtube.com/watch?v=rf6uf3jNjbo
  author: Reducible

bib-algorithms:
  type: book
  title: Introduction to Algorithms
  edition: 4
  author:
    - Thomas H. Cormen
    - Charles E. Leiserson
    - Ronald L. Rivest
    - Clifford Stein
  serial-number:
    isbn: 978-0-262-04630-5
  publisher: MIT Press
  url: http://mitpress.mit.edu/algorithms

bib-partition-function:
  type: thesis
  title: The Partition Function Revisited
  author: M. Ram Murty
  organization: Queen's University at Kingston
  url: https://mast.queensu.ca/~murty/partition.pdf

bib-multivariable-induction:
  type: web
  title: Mathematical Induction
  url:
    value: https://en.wikipedia.org/wiki/Mathematical_induction#Induction_on_more_than_one_counter
    date: 2024-09-24

bib-rodcutting:
  type: chapter
  title: Rod cutting
  author: Jessica Su
  organization: Leland Stanford Junior University
  url:
    value: https://web.stanford.edu/class/archive/cs/cs161/cs161.1168/lecture12.pdf
    date: 2024-09-25
  parent:
    type: article
    title: Dynamic Programming

bib-avl-video:
  type: video
  title: AVL Trees & Rotations (Self-Balancing Binary Search Trees)
  author: Back To Back SWE
  url:
    value: https://www.youtube.com/watch?v=vRwi_UcZGjU
    date: 2024-11-13

bib-avl-vis:
  type: web
  title: AVL Tree Visualization
  author: David Galles
  organization: University of San Francisco
  url:
    value: https://www.cs.usfca.edu/~galles/visualization/AVLtree.html
    date: 2024-11-13
  parent:
    type: web
    title: Data Structure Visualizations

bib-avl-delete:
  type: web
  title: Delete operations on AVL trees
  author: Dr. Shun Yan Cheung
  organization: Emory University
  url:
    value: http://www.cs.emory.edu/~cheung/Courses/253/Syllabus/Trees/AVL-delete.html#case3
    date: 2024-11-14
  
bib-btree-delete:
  type: web
  title: Deletion in a B-tree
  author: Phillip Kirlin
  organization: Rhodes College
  url:
    value: https://www.cs.rhodes.edu/~kirlinp/courses/db/f16/handouts/btrees-deletion.pdf
    date: 2024-11-19

bib-priorityqueue-impl:
  type: misc
  title: IndexMinPQ.java
  author: [Robert Sedgewick, Kevin Wayne]
  organization: Princeton University
  url:
    value: https://algs4.cs.princeton.edu/24pq/IndexMinPQ.java.html
    date: 2025-01-02
  parent:
    type: chapter
    title: Priority Queues
    url:
      value: https://algs4.cs.princeton.edu/24pq/
      date: 2025-01-02
    parent:
      type: book
      title: Algorithms, 4th Edition

bib-hash-quadratic-probing:
  type: video
  title: "Hash Tables: Quadratic Probing"
  author: Clayton Cafiero
  organization: University of Vermont
  url:
    value: https://www.uvm.edu/~cbcafier/cs2240/content/10_probing/02_quadratic.html
    date: 2024-11-25
  parent:
    type: web
    title: CS 2240 Data Structures and Algorithms
    url: 
      value: https://www.uvm.edu/~cbcafier/cs2240/
      date: 2024-11-25

bib-hash-map:
  type: web
  title: Hashing and HashMaps
  author: Jerry Cain
  organization: Stanford University
  url:
    value: https://web.stanford.edu/class/cs106x/res/handouts/22-Hashing-And-HashMaps.pdf
    date: 2024-11-27
  parent:
    title: "CS106X: Programming Abstractions in C++"
    url:
      value: https://web.stanford.edu/class/cs106x/handouts.html
      date: 2024-11-27

bib-hash-division-method:
  type: web
  title: Primes in Division Method of Hashing
  author: Nitin Verma
  url:
    value: https://mathsanew.com/articles/primes_in_division_method_hashing.pdf
    date: 2024-11-27
  parent:
    name: Maths Anew
    url:
      value: https://mathsanew.com/
      date: 2024-11-27

bib-skiplist-analysis:
  type: web
  title: "Randomized Search Structures: Skip Lists"
  author: Dave Mount
  organization: University of Maryland
  url:
    value: https://www.cs.umd.edu/class/fall2020/cmsc420-0201/Lects/lect09-skip.pdf
    date: 2024-11-30
  parent:
    title: CMSC 420
    issue: 9
  
bib-skiplist-operations:
  type: chapter
  title: "Skip Lists"
  author: OpenDSA Project Contributors
  organization: Virginia Polytechnic Institute and State University
  url:
    value: https://opendsa-server.cs.vt.edu/ODSA/Books/CS3/html/SkipList.html
    date: 2024-11-30
  parent:
    type: web
    title: OpenDSA
    chapter: 15.1

bib-graph-adjacency-array:
  type: chapter
  title: 8.2 Adjacency Arrays - Static Graphs
  author:
    - Peter Sanders
    - Kurt Mehlhorn
    - Martin Dietzfelbinger
    - Roman Dementiev
  organization: Max-Planck-Institut für Informatik
  url:
    value: https://people.mpi-inf.mpg.de/~mehlhorn/ftp/NewToolbox/grepresent.pdf
    date: 2025-01-11
  parent:
    type: book
    title: Sequential and Parallel Algorithms and Data Structures
    url:
      value: https://people.mpi-inf.mpg.de/~mehlhorn/ftp/NewToolbox/
      date: 2025-01-11


  
bib-dfs-iterative:
  type: chapter
  title: Depth-first search and breadth-first search
  author: David Gries
  organization: Cornell University
  url:
    value: https://www.cs.cornell.edu/courses/JavaAndDS/dfs/dfs01.html
    date: 2024-12-14
  parent:
    type: book
    title: JavaHyperText and Data Structures
    author: David Gries et al.
    url:
      value: https://www.cs.cornell.edu/courses/JavaAndDS/
      date: 2024-12-14

bib-adj-mtx-powers:
  type: web
  title: Adjacency Matrix
  author: Patrick Corn et al.
  organization: Brilliant
  url:
    value: https://brilliant.org/wiki/adjacency-matrix/
    date: 2024-12-14
  
bib-mst-proof:
  type: chapter
  title: Minimum Spanning Trees
  author: [Robert Sedgewick, Kevin Wayne]
  url:
    value: https://algs4.cs.princeton.edu/lectures/keynote/43MinimumSpanningTrees.pdf
    date: 2024-12-18
  parent:
    title: Algorithms, 4th Edition
  
bib-bellman-ford:
  type: web
  title: Der Bellman-Ford-Algorithmus
  author: [Melanie Herzog, Wolfgang F. Riedl, Richard Stotz]
  organization: Technische Universität München
  url:
    value: https://algorithms.discrete.ma.tum.de/graph-algorithms/spp-bellman-ford/index_de.html
    date: 2024-12-23
  parent:
    type: web
    title: Graphenalgorithmen anschaulich dargestellt
    url:
      value: https://algorithms.discrete.ma.tum.de/de/
      date: 2024-12-23