rekursionsgleichungen:
  type: article
  title: Lösen von (linearen) Rekursionsgleichungen
  author: Prof. Niels Pinkwart
  date: 2007-02-27
  url: https://www2.inf.h-brs.de/~rhartm2m/tuc/inf1-ws2006-07_zusatzmaterial-rekursionsgleichungen.pdf
