bib-rekursionsgleichungen:
  type: article
  title: Lösen von (linearen) Rekursionsgleichungen
  author: Robert F. P. Hartmann
  date: 2007-02-27
  organization: Technische Universität Clausthal
  url: https://www2.inf.h-brs.de/~rhartm2m/tuc/inf1-ws2006-07_zusatzmaterial-rekursionsgleichungen.pdf

bib-fibonaccis-rabbits:
  type: web
  title: Fibonacci's Rabbits
  organization: Emory Oxford College
  url: https://mathcenter.oxford.emory.edu/site/math125/fibonacciRabbits/

bib-3b1b-eigenvalues:
  type: chapter
  title: Eigenvectors and Eigenvalues
  url: https://www.3blue1brown.com/lessons/eigenvalues
  author: Grant Sanderson
  issue: 14
  parent:
    title: Essence of Linear Algebra

bib-hanoi-reducible:
  type: video
  title: "Towers of Hanoi: A Complete Recursive Visualization"
  url: https://www.youtube.com/watch?v=rf6uf3jNjbo
  author: Reducible

bib-algorithms:
  type: book
  title: Introduction to Algorithms
  edition: 4
  author:
    - Thomas H. Cormen
    - Charles E. Leiserson
    - Ronald L. Rivest
    - Clifford Stein
  serial-number:
    isbn: 978-0-262-04630-5
  publisher: MIT Press
  url: http://mitpress.mit.edu/algorithms

bib-partition-function:
  type: thesis
  title: The Partition Function Revisited
  author: M. Ram Murty
  organization: Queen's University at Kingston
  url: https://mast.queensu.ca/~murty/partition.pdf

bib-multivariable-induction:
  type: web
  title: Mathematical Induction
  url:
    value: https://en.wikipedia.org/wiki/Mathematical_induction#Induction_on_more_than_one_counter
    date: 2024-09-24

bib-rodcutting:
  type: chapter
  title: Rod cutting
  author: Jessica Su
  organization: Leland Stanford Junior University
  url:
    value: https://web.stanford.edu/class/archive/cs/cs161/cs161.1168/lecture12.pdf
    date: 2024-09-25
  parent:
    type: article
    title: Dynamic Programming

bib-avl-video:
  type: video
  title: AVL Trees & Rotations (Self-Balancing Binary Search Trees)
  author: Back To Back SWE
  url:
    value: https://www.youtube.com/watch?v=vRwi_UcZGjU
    date: 2024-11-13

bib-avl-vis:
  type: web
  title: AVL Tree Visualization
  author: David Galles
  organization: University of San Francisco
  url:
    value: https://www.cs.usfca.edu/~galles/visualization/AVLtree.html
    date: 2024-11-13
  parent:
    type: web
    title: Data Structure Visualizations

bib-avl-delete:
  type: web
  title: Delete operations on AVL trees
  author: Dr. Shun Yan Cheung
  organization: Emory University
  url:
    value: http://www.cs.emory.edu/~cheung/Courses/253/Syllabus/Trees/AVL-delete.html#case3
    date: 2024-11-14