bib-rekursionsgleichungen:
  type: article
  title: Lösen von (linearen) Rekursionsgleichungen
  author: Robert F. P. Hartmann
  date: 2007-02-27
  organization: Technische Universität Clausthal
  url: https://www2.inf.h-brs.de/~rhartm2m/tuc/inf1-ws2006-07_zusatzmaterial-rekursionsgleichungen.pdf

bib-fibonaccis-rabbits:
  type: web
  title: Fibonacci's Rabbits
  organization: Emory Oxford College
  url: https://mathcenter.oxford.emory.edu/site/math125/fibonacciRabbits/

bib-3b1b-eigenvalues:
  type: chapter
  title: Eigenvectors and Eigenvalues
  url: https://www.3blue1brown.com/lessons/eigenvalues
  author: Grant Sanderson
  issue: 14
  parent:
    title: Essence of Linear Algebra

bib-hanoi-reducible:
  type: video
  title: "Towers of Hanoi: A Complete Recursive Visualization"
  url: https://www.youtube.com/watch?v=rf6uf3jNjbo
  author: Reducible