name: Compile Typst PDF

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile --font-path . main.typ
      - uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
          token: ${{ secrets.TOKEN }}
      
